name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-and-release:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build app
      run: |
        cd "things-mcp"
        xcodebuild -project "TaskNote Bridge.xcodeproj" \
                   -scheme "TaskNote Bridge" \
                   -configuration Release \
                   -derivedDataPath build \
                   build
                   
    - name: Copy built app
      run: |
        cd "things-mcp"
        cp -R "build/Build/Products/Release/TaskNote Bridge.app" .
        
    - name: Create DMG
      run: |
        cd "things-mcp"
        chmod +x create_release_dmg.sh
        ./create_release_dmg.sh
        
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: TaskNote Bridge ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## TaskNote Bridge ${{ steps.get_version.outputs.VERSION }}
          
          ### 📥 Installation
          1. Download the DMG file below
          2. Open it and drag TaskNote Bridge to Applications
          3. Follow the [Installation Guide](https://github.com/${{ github.repository }}/blob/main/INSTALLATION.md)
          
          ### 🔧 VS Code Setup
          Add this to your VS Code settings.json:
          ```json
          {
              "mcp": {
                  "inputs": [],
                  "servers": {
                      "things-swift": {
                          "command": "/Applications/TaskNote Bridge.app/Contents/Resources/launch_mcp_server.sh",
                          "args": []
                      }
                  }
              }
          }
          ```
          
          ### ✨ Features
          - Complete MCP server for Things 3 and Apple Notes
          - Auto-start server functionality
          - Real-time monitoring and logs
          - VS Code integration ready
          
          ### 📋 Requirements
          - macOS 12.0+ (Monterey or later)
          - Things 3 (Mac App Store)
          - Apple Notes (built-in)
          - VS Code with MCP extension
          
          ### 🐛 Issues
          Report bugs on [GitHub Issues](https://github.com/${{ github.repository }}/issues)
        draft: false
        prerelease: false
        
    - name: Upload DMG to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: things-mcp/TaskNote-Bridge-v1.0.0.dmg
        asset_name: TaskNote-Bridge-${{ steps.get_version.outputs.VERSION }}.dmg
        asset_content_type: application/x-apple-diskimage
